sudo: required
language: ruby
cache: bundler
rvm:
- 2.6.3
branches:
  only:
  - develop
env:
  global:
  - GH_COMMIT_AUTHOR=$(git --no-pager show -s --format='%an' HEAD)
  - GH_COMMIT_EMAIL=$(git --no-pager show -s --format='%ae' HEAD)
before_script:
- sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- nvm install 10.11.0
- nvm use 10.11.0
- node -v
- sudo apt-get update -qq
- sudo apt-get install -y yarn
- yarn -v
- yarn
script:
- bundle exec rake test
- RACK_ENV=production bundle exec rake build
after_success:
- bin/deploy
